### PR TITLE
List gists

### PR DESCRIPTION
**Pull request by kangkyu**

### CODE REVIEW

**Comment by kangkyu** [comment]
> For unauthenticated requests, the rate limit allows for up to 60 requests per hour. Unauthenticated requests are associated with the originating IP address, and not the user making requests.

https://developer.github.com/v3/#rate-limiting

So, we may need a user authentication. But for now, I think we can start with information obtained unauthenticated. I added a note for remaining limit at the bottom of each show page.

screen shot 2018-08-26 at 11 04 44 pm

**Comment by kangkyu** [comment]
Also, we should do pagination at some point. `gists` endpoint has 100 for one page, 30 pages limit. (so 3,000 gists total max)

https://developer.github.com/v3/#pagination

**Comment by kangkyu** [comment]
@jendiamond can you please review when you have time 😄

**Comment by Alex1100** [comment]
Use the new pagy gem for pagination it's amost 30x more performant then kaminari gem and 11x times more performant than will_paginate gem.

**Comment by kangkyu** [comment]
Thank you @Alex1100  I opened a issue for pagination for now. And I think I can merge this pull request, because it seems like there's no big objections 😄

**Pull request merged**
